name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt --quiet
    - name: mypy
      run: |
        mypy maml
    - name: pydocstyle
      run: |
        pydocstyle --count maml
    - name: pylint
      run: |
        pylint maml
    - name: black
      run: |
        black --version
        black --check --diff --color maml
    - name: flake8
      run: |
        flake8 --count --show-source --statistics maml
        # exit-zero treats all errors as warnings.
        flake8 --count --exit-zero --max-complexity=20 --statistics maml